# Generated by Django 5.2.6 on 2025-10-27 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Admin'), ('RRHH', 'RRHH'), ('NOMINA', 'Nómina'), ('JEFATURA', 'Jefatura'), ('SUP_COM', 'Supervisor Comercial'), ('TECNICO', 'Técnico'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('departamento', models.CharField(choices=[('RRHH', 'Recursos Humanos'), ('OPERACIONES', 'Operaciones'), ('VENTAS', 'Ventas'), ('FINANZAS', 'Finanzas'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('saldo_vacaciones_dias', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ComisionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('ventas_totales', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CALCULADA', 'Calculada')], default='PENDIENTE', max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptica.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Usa el primer día del mes, ej: 2025-10-01')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE_FIRMA', 'Pendiente Firma'), ('FIRMADA', 'Firmada')], default='PENDIENTE_FIRMA', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='liquidaciones/')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptica.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('TARDANZA', 'Tardanza')], default='PRESENTE', max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptica.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVacacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('observacion', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptica.empleado')),
            ],
        ),
    ]
