# Generated by Django 5.2.6 on 2025-11-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='comisiones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
