# Generated by Django 5.2.6 on 2025-11-16 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptica', '0002_liquidacion_comisiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptica.empleado')),
            ],
        ),
    ]
