# Generated by Django 5.2.6 on 2025-11-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptica', '0003_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionventa',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='comisionventa',
            name='estado',
            field=models.CharField(default='CALCULADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='comisionventa',
            name='ventas_totales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
