# Generated by Django 5.2.6 on 2025-11-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptica', '0004_alter_comisionventa_comision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionventa',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='comisionventa',
            name='estado',
            field=models.CharField(blank=True, default='CALCULADA', max_length=20),
        ),
    ]
