# Generated by Django 5.2.6 on 2025-11-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptica', '0006_alter_comisionventa_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='comisiones',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='periodo',
            field=models.DateField(help_text='Usa el primer día del mes, ej: 2025-11-01'),
        ),
    ]
