# Generated by Django 4.2.24 on 2025-11-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptica', '0007_alter_liquidacion_comisiones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='firma_empleado',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
