# Generated by Django 4.2.24 on 2025-11-18 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptica', '0008_liquidacion_fecha_firma_liquidacion_firma_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudvacacional',
            name='observacion',
        ),
        migrations.AddField(
            model_name='solicitudvacacional',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 18, 2, 39, 49, 330641, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudvacacional',
            name='dias',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='solicitudvacacional',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
    ]
