# Generated by Django 4.2.24 on 2025-11-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptica', '0009_remove_solicitudvacacional_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo_fijo',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=10),
        ),
    ]
